### ISSUE TITLE
Tool does not detect changes in *.vue component files.

### ISSUE THREAD

**Issue by taylorzane** [vuejs/vue-migration-helper#11]
While I understand this tool is in its infancy, I just want to raise the issue that `*.vue` files are not checked for deprecations.

I'm creating this issue more for the community so that they understand that `*.vue` file detection isn't supported yet.

**Comment by txchen** [comment]
Oh, not supporting .vue make the tool much less useful. :(

**Comment by chrisvfritz** [comment]
@taylorzane @txchen It actually does scan `*.vue` files. Could you please provide a repro with a project where they're not being scanned?

**Comment by taylorzane** [comment]
@chrisvfritz 

Hmm. Unfortunately I can't provide a repo, as it's a private project, but I can say that I specified an exact file (I couldn't scan an entire directory because of issue #10) and I didn't get any warnings.

The file contains this snippet (just added to test the utility)

```html
<div id="foo-bar">
  <template v-for="foo in foos | orderBy 'bar'">
    <input type="text" debounce="1000" v-model="foo.bar"/>
  </template>
<div>
```

and my output from the utility is this:

```sh
$ vue-migration-helper src/components/foo.vue

No deprecated patterns detected. Well done!

Note however that only about 80% of deprecations are detectable with this utility. See the migration guide for the rest:

http://rc.vuejs.org/guide/migration.html
```

Am I just not running into any deprecations that are being detected?

**Comment by taylorzane** [comment]
Actually. After updating to the newest commit (after issue 10 was fixed) I'm able to actually see all deprecation warnings. This apparently was fixed with that, thanks!
