### ISSUE TITLE
Detecting comments as Vue Router routes.

### ISSUE THREAD

**Issue by znck** [vuejs/vue-migration-helper#13]
Comment `/* ... */` is treated as `/*foo` route!

![screen shot 2016-10-01 at 13 26 07](https://cloud.githubusercontent.com/assets/2596484/19012697/a863d74a-87da-11e6-9b3e-0638081bfe13.png)

**Comment by chrisvfritz** [comment]
Interesting - I didn't anticipate the use case of comments wrapped in quotes. This is fixed now.

**Comment by znck** [comment]
@chrisvfritz Comments are not in quotes!

**Comment by chrisvfritz** [comment]
In the example you posted (`'/* Load comments */'`), there appears to be single quotes on either side of the comment. If that's not the case in your code, could you post the exact line (including spaces) that causes the problem, if it's still present?

**Comment by znck** [comment]
Sorry! ` debug('/* Load components */');` Not a bug!

**Comment by chrisvfritz** [comment]
Ah, OK - so there are single quotes on either side. Glad it's working now. 😃
