### ISSUE TITLE
why install from git instead of npm?

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vue-migration-helper#16]
Hello 

This is more a question than an issue: 
- why did you choose to install from git instead of npm? 

thank you

**Comment by chrisvfritz** [comment]
@francoisromain Great question! We do plan to publish to NPM once it's done, but this allows faster development until that time. Whenever I push a new rule, which is often many times per day, publishing that rule for others to use is as simple as a `git push`.

**Comment by francoisromain** [comment]
@chrisvfritz yes it does. Thank you. (I wonder if there is a kind of git hook to automate version bump and npm publish)

Very useful tool btw. It helped a lot in the migration process.

**Comment by chrisvfritz** [comment]
Very possibly, but that in and of itself would be one more thing to set up though. 😕 Glad to hear it's been helping!
