### ISSUE TITLE
Command failed: git -c core.longpaths=true config --get remote.origin.url

### ISSUE THREAD

**Issue by andrerpena** [vuejs/vue-migration-helper#17]
When I run this command:

    npm install --global git://github.com/vuejs/vue-migration-helper.git

I get this:

> npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:207:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
> npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
> npm WARN addRemoteGit     at emitOne (events.js:96:13)
> npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
> npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
> 

I don't know why this is happening but I do have `git` installed.

**Environment:**

OS: Windows 7, running in admin mode.
NPM: 3.9.5
Node: 6.2.2

**Comment by chrisvfritz** [comment]
This kind of error is usually a connectivity issue. Can you try again, in case you were temporarily disconnected from the Internet? If it still doesn't work, it may have also been mistakenly blocked by a corporate firewall.

**Comment by chrisvfritz** [comment]
Assuming this is fixed, since there's been no word and no other repros.
