### ISSUE TITLE
Warning about outdated versions of vue libs in package.json

### ISSUE THREAD

**Issue by netroby** [vuejs/vue-migration-helper#19]
Migration-helper not scan package.json. so the project package.json dependencies still 1.*
```
    "babel-runtime": "^6.0.0",
    "es6-promise": "^3.2.1",
    "vue": "^1.0.21",
    "vue-async-data": "^1.0.2",
    "vue-resource": "^1.0.0",
    "vue-router": "^0.7.13"

```

**Comment by chrisvfritz** [comment]
The helper does scan `.json` files, but doesn't have warnings for these yet. I think that would be a good addition!

**Comment by chrisvfritz** [comment]
This is now fixed.
