### ISSUE TITLE
Add Vuex 2.0 Deprecations (lower priority, as upgrading to Vuex 2.0 is optional for Vue 2)

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-migration-helper#2]
Patterns:
- [ ] `vuex: {` should be replaced by action/mutation/getter/state helpers on methods and computed properties
- [ ] `store.watch('XXX', ...)` -> `store.watch(state => state.XXX, ...)` The 1st argument of `watch` should be the function that returns sub state tree.
- [ ] `middlewares` -> `plugins`
- [ ] `store.dispatch` -> `store.commit` mutations are now triggered by `commit` method.
- [ ] The arguments of `store.dispatch` and `store.commit` is no longer variadic. It now accepts a single payload value as the 2nd argument.
- [ ] `silent` flag for silent dispatch is now declared in 3rd argument options object.
- [ ] payload arguments changes (see https://github.com/vuejs/vue-migration-helper/issues/2#issuecomment-252259002)

**Comment by ktsn** [comment]
List updated 😄

**Comment by chrisvfritz** [comment]
@ktsn Thanks! These look great!

**Comment by chrisvfritz** [comment]
@ktsn How would you feel about having all the migration info in the main guide, but on a separate `Migration from vuex 1.x` page? My thinking is it would make it simple to keep the same format for all the migrations and people could look in only one place while migrating. Then it could be linked to from the vuex docs.

**Comment by ktsn** [comment]
Sounds good to me.

**Comment by mckaydavis** [comment]
For the `vuex` deprecation warnings, please be sure to suggest use of the `mapGetters`, `mapActions`, `mapMutations`, and `mapState` helper functions. reference: vuejs/vuex/#236

**Comment by chrisvfritz** [comment]
@mckaydavis Planning on it. 😃 👍

**Comment by TheDutchCoder** [comment]
Can you add the change in actions as well?
Vuex2 only takes 1 payload argument, whereas Vuex1 could take any amount of arguments.

Vuex 1 Example:
```js
export const addToCart = ({ dispatch, state }, product, foo, bar) => {
  // Use product, foo, bar.
}
```

Vuex 2 Example: 
```js
export const addToCart = ({ dispatch, state }, payload) => {
   // Use payload.product, payload.foo, payload.bar.
}
```

**Comment by chrisvfritz** [comment]
@TheDutchCoder Yes, we should be able to catch that!

**Comment by chrisvfritz** [comment]
Closing, as the tool already migrates people to a minimal version of Vuex that allows them to use Vue 2, which is the primary purpose of the tool.
