### ISSUE TITLE
helper is also reading unrelated files ex. .scss

### ISSUE THREAD

**Issue by rhysburnie** [vuejs/vue-migration-helper#25]
The helper is reading files that aren't relevant.

For example: 

```
 Rename $index to index and explicity declare it (e.g. v-for="(item, index) in items")
  Line 9: src/assets/scss/_font-loader.scss
```

the `$index` in that file has nothing to do with vue its a sass variable in a sass function

**Comment by rhysburnie** [comment]
Also in another native js file that happened to have a function named `init` was receiving this message: `Replace init with beforeCreate` - its not in any way a vue file.

**Comment by rhysburnie** [comment]
Also I had some markdown documentation for my project with the line:

> if all else fails the app will fallback to use fake device data (which is the case in development...

migration tool says `Replace the data route hook with a watcher that reacts to $route changes` just because it happens to have the word _data_ in the paragraph

**Comment by rhysburnie** [comment]
```
<input type="tel" v-model="userPhone" placeholder="Phone number"
```

warns: `Refactor number to a v-model modifier: v-model.number="userPhone"`

only because the placeholder has the word _number_ in it, surely should only be a message if you were using the number attr

**Comment by chrisvfritz** [comment]
Thanks for reporting these! If you update the migration helper, I believe they should all be fixed now. Can you confirm?

**Comment by chrisvfritz** [comment]
@rhysburnie Just pinging on this. Do you still experience any of these issues with the latest update?

**Comment by rhysburnie** [comment]
In the process of using the update, a few of the issues exist will post as I come across them.

One of them is Im getting this in a markdown file `Replace route.mixin with route.meta.mixin`

The line in the file is simply linking to another markdown file called: `track-route.mixin.md`

**Comment by chrisvfritz** [comment]
@rhysburnie Thanks! That one should now be fixed too.

**Comment by chrisvfritz** [comment]
@rhysburnie Closing this for now, as I believe all the items you brought up should now be resolved. If you find anything else, feel free to open new issues. 😃  Thanks for your help!
