### ISSUE TITLE
Add Vue-Router Deprecations

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-migration-helper#3]
- [x] Update `history: true` to `mode: 'history'`
- [x] `router.map` should be a `routes` option on a new router instance. The route definition should also be an array instead of an object.
- [x] `router.start` -  should provide the router instance to the root vue instance (`new Vue({ router })`)
- [x] `activate` -> `beforeRouteEnter` in component
- [x] `canActivate` -> `beforeEnter` in route
- [x] `deactivate` -> component lifecycle
- [x] `canDeactivate` -> `beforeRouteLeave` in component
- [x] `canReuse` -> removed
- [x] `v-link` -> `<router-link>`
- [x] `saveScrollPosition` -> `scrollBehavior` in Router options
- [x] `router.redirect` -> `redirect` in `routes` in Router options
- [x] `router.alias` -> `alias` in `routes` in Router options
- [x] `abstract` (replaced by `mode`)
- [x] `root` (replaced by `base`)
- [x] `hashbang` (removed since the hashbang is no longer required for Google to crawl the URL)
- [x] `transitionOnLoad` (removed because Vue 2.0 has explicit `appear` transition control)
- [x] `suppressTransitionError` (removed due to hooks simplification)
- [x] The old `router.go()` is now `router.push()`, but `router.go(number)` is now a thing
- [x] `subroutes` -> `children` in route definition
- [x] `keepAlive` -> `keep-alive` attribute is deprecated, please use `<keep-alive>` component to wrap around `<router-view>`, and refer to Vue 2.0 docs.
- [x] `v-link-active` -> `v-link-active` is deprecated, please use `<router-link>` component's `activeClass` prop.
- [x] `data` -> Use a watcher on $route to react to route changes (e.g. fetch new data based on new route params - [Example](https://github.com/vuejs/vue-router/tree/next/examples/data-fetching)) // copied from release notes
- [x] `router.on` -> Removed. XXX `router.match = createMatcher([routeConfig, ...router.options.routes])`
- [x] `$loadingRouteData` should be replaced with a custom property, e.g. `loading`
- [x] `/category/*tax` should be changed to `/category/:tax+` (uses [path-to-regexp](https://github.com/pillarjs/path-to-regexp))
- [x] Route records of the matched routes are no longer merged into `$route`.

For the router, it might also be worth building a plugin that validates a router object with Joi or something.

**Comment by posva** [comment]
List updated 🎉

**Comment by chrisvfritz** [comment]
> `hashbang` (removed since the hashbang is no longer required for Google to crawl the URL)

@posva I might be reading it incorrectly, but isn't `hashbang` (renamed to `hash`) still [the default mode](https://github.com/vuejs/vue-router/blob/next/src/index.js#L30)? Or is `hash` a new unrelated mode?

**Comment by fnlctrl** [comment]
@posva 
updated keep-alive, v-link-active, data, suppressTransitionError
removed linkActiveClass section as it's not deprecated
I'm not sure about `router.on`.. never heard of it before..

**Comment by posva** [comment]
@chrisvfritz It was an option that could only be used alongside hash mode to prefix routes with `#!`. Now, when using hash mode you always get `#` as the prefix without the bang.
Basically the default behaviour is like passing `false`

**Comment by posva** [comment]
@fnlctrl Thanks! Well, I looked into code and it looks like it doesn't exist anymore

**Comment by chrisvfritz** [comment]
@posva Thanks for clarifying!

**Comment by probil** [comment]
It seem like meta property `$loadingRouteData` is deprected now. (got error about that in console)
It should be replaced with custom property, e.g. `loading`

* Look at the example here
https://github.com/vuejs/vue-router/blob/next/examples/data-fetching/Post.vue

* `$loadingRouteData` in 1.X docs
http://router.vuejs.org/en/pipeline/data.html
(look and the *Details* section)

**Comment by probil** [comment]
Also, I have discovered that some route matching rules was changed.
For example, `/category/*tax` no more works and should be changed to `/category/:tax+`

**Comment by chrisvfritz** [comment]
@probil Thanks!

**Comment by chrisvfritz** [comment]
@posva @fnlctrl How would you feel about having all the migration info in the main guide, but on a separate `Migration from vue-router 1.x` page? My thinking is it would make it simple to keep the same format for all the migrations and people could look in only one place while migrating. Then it could be linked to from the vue-router docs.

**Comment by fnlctrl** [comment]
Another deprecation that needs to be covered: (Though it may be hard to be regex matched...)
Route records of the matched routes are no longer merged into `$route`.
https://github.com/vuejs/vue-router/issues/704

Maybe we can warn if someone accessed `route.foo` where `foo` isn't a valid [route record field](https://github.com/vuejs/vue-router/blob/dev/flow/declarations.js#L46-L60).

**Comment by chrisvfritz** [comment]
@fnlctrl Good idea. We'll also want to exclude anything in the v0.7+.

**Comment by fnlctrl** [comment]
Seems we missed `router.start`... added to the list.
https://github.com/vuejs/vue/issues/3865

**Comment by chrisvfritz** [comment]
Done. 😄
