### ISSUE TITLE
vue-migration-tool vue-migration-tool runs out of memory

### ISSUE THREAD

**Issue by TomMorison12** [vuejs/vue-migration-helper#30]
I just installed the vue migration helper on my machine and I tried running `vue-migration-tool src ~/Code/CSToss` and I get the following error:

> er src ~/Code/CSToss
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOMEM: not enough memory, open '/home/vagrant/Code/CSToss/vendor/psy/psysh/test/fixtures/config.php'
    at Error (native)

I have no idea what's going on. i have not used Vue.js that much and I am not sure why this error is comming up. I am using Laravel Homestead to run this command.

**Comment by yyx990803** [comment]
You probably want to limit it to only the js/vue files in your project.

**Comment by chrisvfritz** [comment]
I'm guessing the `vendor` directory has a _lot_ of files, which would be the source of the issue. I just published a new patch that adds directories called `vendor` to a blacklist, so they won't be scanned and you shouldn't encounter this issue after updating. Also, in the future, scans will also go much faster (typically less than a few seconds) if you only scan the specific directories where you have Vue-related code.
