### ISSUE TITLE
Add check for interpolated value in "value" attribute

### ISSUE THREAD

**Issue by duebbert** [vuejs/vue-migration-helper#32]
Old 1.x code in template:
`<input value="{{ example }}">`

Should be easily detectable and suggest to rewrite to:
`<input v-bind:value="example">`

Just had a project with lots of these. Vue-loader picks them up but not the (very useful! Thank you!) migration tool.

**Comment by chrisvfritz** [comment]
Glad to hear you're finding it useful! 😄  Your example should currently be flagged by [this rule](https://github.com/vuejs/vue-migration-helper/blob/master/rules/vue/interpolation-within-attributes.spec.js). I just tested it to confirm and it seemed to work:

```
1. Update value="{{ example }}" to v-bind:value="example"
  Line 1: index.html
  Reason: Interpolation within attributes has been removed
  More info: http://vuejs.org/guide/migration.html#Interpolation-within-Attributes
```

Would you be able to share an example file where it didn't work?

**Comment by duebbert** [comment]
Ok, I really don't know why I wrote the above because of course the tool did flag those up. Might be that it missed some cases but cannot reproduce at the moment. So please ignore my issue...
