### ISSUE TITLE
[proposal]add `autofix` option

### ISSUE THREAD

**Issue by Aladdin-ADD** [vuejs/vue-migration-helper#33]
This tool is great. can we go further, to provide an option like`--autofix`? As some problems can be easily fixed. eg.
```js
<a href="{{ $url }}">test</a>
```
can be fixed to something like:
```js
<a :href="$url">test</a>
```

This can be very useful to some developers.you recon?:laughing:

**Comment by chrisvfritz** [comment]
I think it would be a nice feature if it worked reliably, but due to the strategy we use here, there are sometimes false positives - so code could actually be changed when it has nothing to do with Vue! 😬  For that reason, I don't think an autofix option is a good idea unfortunately.
