### ISSUE TITLE
Detecting gulpfile globs as Vue Router routes

### ISSUE THREAD

**Issue by tonystaark** [vuejs/vue-migration-helper#34]
![gulpfile issue](https://cloud.githubusercontent.com/assets/16837659/25427773/2bd5db5a-2aa6-11e7-97d4-801a23dfd002.png)

Suggest to add `gulpfile.js` into your list of exception for detecting as Vue Router routes.

**Comment by chrisvfritz** [comment]
Done. 🙂  Thanks for the suggestion!
