### ISSUE TITLE
能否生成迁移报告？

### ISSUE THREAD

**Issue by zuolin777** [vuejs/vue-migration-helper#36]
目前我的项目有500+需要更改的地方，如果生成报告会比较方便查看

**Comment by kazupon** [comment]
Sorry, Could you tell us English please ?

**Comment by zuolin777** [comment]
Sorry about that.Can you generate migration reports??
Currently, my project has 500+ where it needs to be changed, and it would be easier to generate reports

**Comment by kazupon** [comment]
Thank you for you feedback with english :)

You can use the redirection the below:

```sh
$ vue-migration-helper src/ > report.txt
```
