### ISSUE TITLE
`require` path error related to `recursive-readdir-sync`

### ISSUE THREAD

**Issue by whitetrefoil** [vuejs/vue-migration-helper#4]
It seems that `recursive-readdir-sync` returns full abspath instead of relative path when passed in an abspath.  So [this line](https://github.com/vuejs/vue-migration-helper/blob/master/helpers/check-for-deprecations.js#L14) will cause problem...
```
Me@localhost:~/Workspace/helloworld $> ./node_modules/.bin/vue-migration-helper

Error: Cannot find module '/Users/Me/Workspace/helloworld/node_modules/vue-migration-helper/rules/Users/Me/Workspace/helloworld/node_modules/vue-migration-helper/rules/vue/array-prototype-remove.js'
```
Tried on OSX w/ node `v6.6.0` & Ubuntu w/ node `v6.4.0`, `recursive-readdir-sync` is `v1.0.6`.  Not tried on Windows yet.

**Comment by chrisvfritz** [comment]
Sorry about that! This has now been fixed and I added some e2e tests to catch things like that in the future.
