### ISSUE TITLE
bash: vue-migration-tool: command not found

### ISSUE THREAD

**Issue by MarioCarloni** [vuejs/vue-migration-helper#41]
I've installed the tool using `npm i --global vue-migration-helper`, restarted the computer, navigated to my vue-1 project directory using node command prompt, then ran `vue-migration-helper`. 

I receive an error: `bash: vue-migration-helper: command not found`.

I'm running Node v8 and npm v5 (newest LTS release as of this date) on Windows 10.

**Comment by chrisvfritz** [comment]
It sounds like the directory that NPM's installing global modules to is not in your `PATH`. You can [use this](https://stackoverflow.com/questions/33819757/global-npm-install-location-on-windows/43398997) to find out where they are, but how exactly you add that directory will depend on the terminal you're using.

In the meantime, I'll close this as it's not actually an issue with this tool.
