### ISSUE TITLE
Package version constraint parsing seems off

### ISSUE THREAD

**Issue by ivuorinen** [vuejs/vue-migration-helper#42]
Running `vue-migration-helper` with `vue-router:^3.0.2` and `vuex:^3.0.1` suggests following migrations:

```
1. Replace "vue-router": "^3.0.2" with "vue-router": "^2.0.0", then run: npm install
  Line 22: package.json
  Reason: If you are using pre-2.0 Vue Router through NPM, you have to update it in your package.json file
  More info: http://vuejs.org/guide/migration-vue-router.html#

2. Replace "vuex": "^3.1.0" with "vuex": "^1.0.0", then run: npm install
  Line 23: package.json
  Reason: Vuex 1.0 is the earliest supported version compatible with Vue 2.0
  More info: http://vuejs.org/guide/migration-vuex.html#
```

It looks like the check assumes anything that's not 2.* (for vue-router) is wrong:

- https://github.com/vuejs/vue-migration-helper/blob/3dc64a981f3b66b3b28b3b6e4ea7e913a67e4f3e/rules/vue-router/vue-router-dependency.js#L6
- https://github.com/vuejs/vue-migration-helper/blob/3dc64a981f3b66b3b28b3b6e4ea7e913a67e4f3e/rules/vuex/vuex-dependency.js#L6

Should/Could it be changed to use `semver.satisfies('^2.0.0', [package.json data])` and `^1.0.0`?

**Comment by chrisvfritz** [comment]
Thanks for reporting this. 🙂 The way the matching works here, we'd have to stick with regex rather than the more optimal `semver.satisfies`, but a PR with a fix and new tests would be very welcome for this! Otherwise, I'll try to get to it as soon as I'm able.

**Comment by ivuorinen** [comment]
Closing as resolved, thanks for accepting the PR!

**Comment by chrisvfritz** [comment]
Thanks for providing it! 🙂
