### ISSUE TITLE
[Error] Wrong more info link

### ISSUE THREAD

**Issue by tetreum** [vuejs/vue-migration-helper#9]
> 35. Replace history: true with mode: 'history'

>   Line 41: src/main.js

>   Reason: In vue-router, all modes (e.g. history, hash, abstract) are now set through the new mode option

>   More info: http://rc.vuejs.org/guide/migration.html#replace-false-deprecated

I couldn't find where it should point as http://router.vuejs.org/en/api/options.html#mode doesn't display any usage example.

¡Thank you for making this tool!

**Comment by chrisvfritz** [comment]
The Vue Router migration guide is still being developed (should be done hopefully later today). At that time, I'll have real links to add to router rules. 😃

**Comment by tetreum** [comment]
Ups! Closing issue then!
